[package]
name = "lisa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
rand = { version = "0.8.5", features = ["small_rng"] }
[dependencies.sdl2]
    version = "0.36.0"
    default-features = false
    features = ["ttf", "gfx"]
